language: python
python: "2.7.13"

# Needed to enable Travis CI for gh-pages branches, see:
#   https://github.com/travis-ci/travis-core/pull/137
branches:
  only:
    - gh-pages

script:
  - ./pants --version
  - ./pants list ::

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    
    - os: osx
      osx_image: xcode7.3
      language: generic

    - os: osx
      osx_image: xcode8.3.3
      language: generic

    - os: osx
      osx_image: xcode9.1
      language: generic

    - os: linux
      dist: precise
      sudo: required

    - os: linux
      dist: trusty
      sudo: false


