language: python
python: "2.7.13"

script:
  - ./pants --version
  - ./pants list ::

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    
    - os: osx
      osx_image: xcode7.3
      language: generic

    - os: osx
      osx_image: xcode8.3.3
      language: generic

    - os: osx
      osx_image: xcode9.1
      language: generic

    - os: linux
      dist: precise
      sudo: required

    - os: linux
      dist: trusty
      sudo: false


